L1(t):= t * (1 - t);
L2(t):= t/2 * (1 - t/2);

L: L1(t)/2 + L2(t)/2;
L: factor(L);

r(x):= round(x * 100)/100;

t0: 0.4;
thru 5 do (
printf(true, "~,2f~%", r(t0)),
w1: L1(t0)/(L1(t0) + L2(t0)),
Q: w1 * log(L1(t)) + (1 - w1) * log(L2(t)),
dQ: diff(Q, t),
sol: solve(dQ),
t0: float(rhs(sol[1])));

/* draw2d(explicit(L, t, 0, 1)); */

Q: 'al * log(L1('t)) + (1 - 'al) * log(L2('t));
dQ: fullratsimp(diff(Q, 't));

sol: solve(dQ, 't);
