P1: 1/2;
P2a: 1/6;
P2b: 1/6;
P2c: 1/6;

L1: 1/2 * 1/2 * 1/2;
L2a: 1/2 * 1/2 * 1/2;
L2b: 1/3 * 2/3 * 2/3;
L2c: 2/3 * 1/3 * 1/3;


E: P1*L1 + P2a*L2a + P2b*L2b + P2c*L2c;

O1: L1*P1/E;
O2a: L2a*P2a/E;
O2b: L2b*P2b/E;
O2c: L2c*P2c/E;

r(x):= round(x * 100)/100;

printf(true, "~,2f ~,2f ~,2f ~,2f~%", r(O1), r(O2a), r(O2b), r(O2c));
printf(true, "~,2g ~,2g ~,2g ~,2g~%", r(P1), r(P2a), r(P2b), r(P2c));
